"""Protocol draft and methodology report generators.

The engine produces two related artifacts:
- ``protocol_draft.md`` at project root, only when the user opts in before
  search execution. This is a prospective PRISMA-P-style draft.
- ``methodology_report.md`` at export time. This is the mandatory
  retrospective methods record with executed searches, flow counts, screening
  breakdowns, and audit pointers.

Design notes:
- The draft does not read the project database. It only uses scoping state,
  curated vocabulary, and query files on disk.
- The methodology report reuses the scoping sections, then adds DB-derived
  retrospective sections.
- The engine does not claim full PRISMA-P checklist compliance. The output is
  scaffolding for researchers to verify and refine when formal registration or
  publication rigor is needed.
"""
from __future__ import annotations

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import yaml

from .store import ProjectConfig, ProjectPaths


SLR_ENGINE_VERSION = "1.0"


HONESTY_DISCLAIMER = """\
> **A note on this methodology artifact.** This document was generated by the
> SLR-Engine, which compresses methodology that researchers traditionally do by
> hand over weeks. SLR-Engine offers to walk users through the academic steps
> (topic -> aim -> research questions -> framework -> eligibility -> search ->
> screening), but users may skip steps by telling the agent what they already
> have. The outputs are designed to be defensible, but they are *less
> methodologically honest than a process driven by an experienced human
> reviewer*. If aiming for academic-rigor publication, treat this document as
> **scaffolding to verify and refine**. If using this for practical
> knowledge-gathering - a market scan, competitive analysis, or knowledge
> management catalog - this document is a complete record of the review.
"""


REGISTRATION_NOTE = """\
## Registration note

This draft aligns with the spirit of PRISMA-P as a prospective commitment
document, but the engine does not register it automatically and does not claim
full checklist compliance. For formal use, copy the relevant sections into the
target registry or submission system and verify all registry-specific fields.

Common registries:
- **PROSPERO** - health/social-care reviews; free; web-form submission.
  <https://www.crd.york.ac.uk/PROSPERO/>
- **OSF Registries** - broader scope; free; web interface.
  <https://osf.io/registries>
- **INPLASY** - alternative to PROSPERO.
  <https://inplasy.com/>
"""


_QUERY_PLACEHOLDER_MARKERS = (
    "<replace",
    "<concept",
    "<synonym",
    "<narrow concept",
    "<another narrow",
    "<arxiv boolean",
    "replace placeholders",
)


def hallucination_caveat(n_hypotheses: int) -> str:
    """Hypothesis-tracking risk note.

    The caveat scales with count and is never zero risk when hypotheses are
    present.
    """
    if n_hypotheses == 0:
        return ""
    risk_phrase = (
        "low but non-zero" if n_hypotheses == 1
        else "moderate" if n_hypotheses <= 3
        else "elevated"
    )
    extra = ""
    if n_hypotheses > 3:
        extra = (
            f"\n\n> The engine recommends a soft cap of 3 hypotheses. This "
            f"review tracks {n_hypotheses}, above the recommended cap. "
            "Spot-check rates should be increased proportionally."
        )
    return f"""\
## Note on hypothesis tracking and LLM extraction

This review tracks **{n_hypotheses} {'hypothesis' if n_hypotheses == 1 else 'hypotheses'}**
using the LLM configured for full-text screening. When the LLM reads each
paper, it produces - in the same call - both the screening decision and the
per-hypothesis support/refute/mixed/unclear judgment.

**This is not a retrieval system (no RAG, no vector search, no separate
retriever).** The same model that reads the paper makes the call.

Two consequences for interpreting the synthesis:

1. **False-positive risk is {risk_phrase} at this hypothesis count and
   grows with count.** Even with one hypothesis, the LLM can flag a paper
   as "supports H1" when the paper only tangentially relates. With more
   than three, the risk climbs because the model is tracking multiple
   claims simultaneously and may pattern-match weakly.

2. **Mitigation is human spot-checking, not algorithmic.** Recommended
   practice: read 5+ randomly selected records per hypothesis before
   relying on the synthesis. For any hypothesis where spot-check
   disagreement exceeds 20%, re-screen that hypothesis manually. The
   `hypotheses_table.csv` includes the LLM's reasoning per row so
   individual calls can be audited.{extra}
"""


def _generated_at() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _format_framework(framework: Optional[dict]) -> str:
    if not framework:
        return "Not specified.\n"
    ftype = framework.get("type", "custom")
    slots = framework.get("slots") or {}
    if ftype == "picoc":
        label = (
            "**PICOC** (Population, Intervention, Comparison, Outcome, "
            "Context; Petticrew & Roberts 2008; adopted in software "
            "engineering by Kitchenham et al. 2007)"
        )
    elif ftype == "custom":
        label = "**Custom framework** (slots described by user)"
    else:
        label = f"**{ftype}**"

    out = [f"Framework: {label}\n"]
    if slots:
        out.append("\nSlots:\n")
        for slot_name, filling in slots.items():
            out.append(f"- **{slot_name.title()}**: {filling}")
        out.append("")
    return "\n".join(out)


def _format_hypotheses(hypotheses: list[dict]) -> str:
    if not hypotheses:
        return "No hypotheses declared. This is an exploratory review.\n"
    out = []
    for h in hypotheses:
        hid = h.get("id", "?")
        stmt = h.get("statement", "")
        rat = h.get("rationale", "")
        out.append(f"### {hid}\n\n**Statement:** {stmt}\n")
        if rat:
            out.append(f"**Rationale:** {rat}\n")
    return "\n".join(out)


def _format_criteria(criteria: list[dict]) -> str:
    if not criteria:
        return "_(none specified)_\n"
    return "\n".join(
        f"- **{c.get('id', '?')}**: {c.get('text', '')}"
        for c in criteria
    ) + "\n"


def _format_seeds(seeds: dict) -> str:
    out = []
    papers = (seeds or {}).get("papers") or []
    if papers:
        out.append("**Seed papers:**")
        for p in papers:
            doi = p.get("doi", "")
            openalex = p.get("openalex", "")
            pdf = p.get("pdf", "")
            ref = doi or openalex or pdf or json.dumps(p, ensure_ascii=False)
            note = p.get("note", "")
            out.append(f"- {ref}{' - ' + note if note else ''}")
    links = (seeds or {}).get("links") or []
    if links:
        out.append("\n**Seed links:**")
        for link in links:
            out.append(f"- {link}")
    if not out:
        return "_(none)_\n"
    return "\n".join(out) + "\n"


def _raw_project_yaml(paths: ProjectPaths) -> dict:
    path = paths.root / "project.yaml"
    if not path.exists():
        return {}
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _enabled_sources(cfg: ProjectConfig) -> list[str]:
    return [
        k for k, v in (cfg.sources or {}).items()
        if v is True or v == "manual"
    ]


def _format_information_sources(cfg: ProjectConfig, *, prospective: bool) -> str:
    enabled_sources = _enabled_sources(cfg)
    label = "Databases planned:" if prospective else "Databases configured:"
    lines = [label]
    if enabled_sources:
        for source in enabled_sources:
            marker = " (manual export)" if cfg.sources.get(source) == "manual" else ""
            lines.append(f"- {source}{marker}")
    else:
        lines.append("- _(none configured)_")
    if cfg.date_from or cfg.date_to:
        lines.append("")
        lines.append(
            f"Date range: {cfg.date_from or 'unspecified'} "
            f"to {cfg.date_to or 'present'}"
        )
    if cfg.languages:
        lines.append("")
        lines.append(f"Languages: {', '.join(cfg.languages)}")
    return "\n".join(lines) + "\n"


def _load_vocabulary(paths: ProjectPaths) -> Optional[dict]:
    vocab_path = paths.root / "seeds" / "_vocabulary.json"
    if not vocab_path.exists():
        return None
    try:
        return json.loads(vocab_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def _format_concept_clusters(vocab: Optional[dict]) -> str:
    clusters = (vocab or {}).get("clusters") or []
    if not clusters:
        return "_No curated vocabulary clusters found yet._\n"
    out = []
    for cluster in clusters:
        name = cluster.get("name") or "Unnamed cluster"
        terms = cluster.get("terms") or []
        rationale = cluster.get("rationale")
        out.append(f"- **{name}**: {', '.join(str(t) for t in terms)}")
        if rationale:
            out.append(f"  Rationale: {rationale}")
    return "\n".join(out) + "\n"


def _strip_txt_query_comments(text: str) -> str:
    lines = [
        line.rstrip()
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    return "\n".join(lines).strip()


def _query_display_text(path: Path, text: str) -> str:
    if path.suffix.lower() == ".txt":
        return _strip_txt_query_comments(text)
    return text.strip()


def _looks_like_unfilled_query(path: Path, text: str) -> bool:
    display = _query_display_text(path, text)
    if not display:
        return True
    lowered = display.lower()
    return any(marker in lowered for marker in _QUERY_PLACEHOLDER_MARKERS)


def _filled_query_files(paths: ProjectPaths) -> tuple[list[tuple[str, str]], list[str]]:
    queries_dir = paths.queries
    if not queries_dir.exists():
        return [], []
    files = sorted(list(queries_dir.glob("*.txt")) + list(queries_dir.glob("*.json")))
    filled: list[tuple[str, str]] = []
    unfilled: list[str] = []
    for path in files:
        text = path.read_text(encoding="utf-8-sig")
        display = _query_display_text(path, text)
        if _looks_like_unfilled_query(path, text):
            unfilled.append(path.name)
        else:
            filled.append((path.name, display))
    return filled, unfilled


def _format_planned_search_strategy(cfg: ProjectConfig, paths: ProjectPaths) -> str:
    vocab = _load_vocabulary(paths)
    filled, unfilled = _filled_query_files(paths)

    out = ["**Concept clusters:**\n"]
    out.append(_format_concept_clusters(vocab))

    if filled:
        out.append("\n**Draft query files available before execution:**\n")
        for name, text in filled:
            out.append(f"### {name}\n")
            out.append(f"```\n{text}\n```\n")
    else:
        out.append(
            "\nNo filled per-source query files were found yet. Run "
            "`scripts/01_generate_queries.py`, replace the placeholders, and "
            "review the literal strings before search execution.\n"
        )

    if unfilled:
        out.append("\nQuery files still looking like templates:\n")
        for name in unfilled:
            out.append(f"- {name}")
        out.append("")

    planned = _enabled_sources(cfg)
    if planned:
        out.append("\nConfigured sources for these queries:\n")
        for source in planned:
            out.append(f"- {source}")
        out.append("")

    return "\n".join(out)


def _format_screening_plan(cfg: ProjectConfig, *, prospective: bool) -> str:
    verb = "planned" if prospective else "configured"
    if cfg.llm and not cfg.uses_agent_judgment():
        provider = cfg.llm.get("provider", "?")
        model = cfg.llm.get("model", "?")
        return (
            f"Model-backed screening was {verb}. Provider: {provider}; "
            f"model: {model}. Model recommendations are auditable separately "
            "from final human decisions.\n"
        )
    if cfg.llm and cfg.uses_agent_judgment():
        return (
            f"External-agent handoff screening was {verb}. The engine stages "
            "prompt packets and editable review files; final decisions are "
            "committed through the review scripts.\n"
        )
    return (
        f"Manual/agent-assisted screening was {verb}. The reviewer applies "
        "the inclusion and exclusion criteria literally, with decisions "
        "recorded in the project database.\n"
    )


def _format_data_extraction(cfg: ProjectConfig, *, prospective: bool) -> str:
    prefix = "Planned extraction schema" if prospective else "Extraction schema"
    if cfg.extraction:
        preset = cfg.extraction.get("preset", "generic")
        custom = cfg.extraction.get("custom_fields") or []
        out = [f"{prefix}: preset=**{preset}**"]
        if custom:
            out.append(f", with {len(custom)} custom field(s)")
        out.append(".\n\nFields extracted per included paper:")
        try:
            from .llm import get_extraction_fields

            for field in get_extraction_fields(cfg.extraction):
                desc = str(field.get("description", ""))[:100]
                out.append(
                    f"- **{field['name']}** ({field.get('type', 'string')}): {desc}"
                )
        except Exception:
            pass
        out.append("")
        return "\n".join(out)
    return (
        f"{prefix}: generic preset (summary, context, approach, "
        "data_or_setup, key_results, relevance_notes).\n"
    )


def _format_quality_assessment_plan(paths: ProjectPaths, *, prospective: bool) -> str:
    raw = _raw_project_yaml(paths)
    qa = raw.get("quality_assessment")
    if not qa:
        return "Planned risk-of-bias approach: to be determined.\n"
    label = "Planned risk-of-bias approach" if prospective else "Risk-of-bias approach"
    if isinstance(qa, str):
        return f"{label}: {qa}\n"
    if isinstance(qa, dict):
        lines = [f"{label}:"]
        for key, value in qa.items():
            if isinstance(value, (dict, list)):
                rendered = json.dumps(value, ensure_ascii=False)
            else:
                rendered = str(value)
            lines.append(f"- **{key}**: {rendered}")
        return "\n".join(lines) + "\n"
    return f"{label}: {json.dumps(qa, ensure_ascii=False)}\n"


def _base_sections(
    cfg: ProjectConfig,
    paths: ProjectPaths,
    *,
    title: str,
    prospective: bool,
) -> list[str]:
    sections = [
        f"# {title} - {cfg.project_id}\n",
        f"_Generated: {_generated_at()}_\n",
        HONESTY_DISCLAIMER,
        "\n---\n",
        "## Topic\n",
        (cfg.topic or "_(not specified)_") + "\n",
        "## Aim\n",
        (cfg.aim or "_(not specified)_") + "\n",
        "## Research questions\n",
    ]

    if cfg.research_questions:
        import re

        for i, rq in enumerate(cfg.research_questions, 1):
            cleaned = re.sub(r"^\s*RQ\s*\d+\s*[:.\-]\s*", "", rq, flags=re.I).strip()
            sections.append(f"**RQ{i}:** {cleaned}\n")
    else:
        sections.append("_(not specified - review topic was used as informal review question)_\n")

    sections.extend([
        "## Framework\n",
        _format_framework(cfg.framework),
        "## Hypotheses\n",
        _format_hypotheses(cfg.hypotheses),
    ])

    if cfg.hypotheses:
        sections.append(hallucination_caveat(len(cfg.hypotheses)))

    search_heading = "## Planned search strategy\n" if prospective else "## Search strategy from scoping\n"
    screening_heading = "## Planned screening procedure\n" if prospective else "## Screening approach\n"
    extraction_heading = "## Planned data extraction fields\n" if prospective else "## Data extraction fields\n"
    rob_heading = "## Planned risk-of-bias approach\n" if prospective else "## Risk-of-bias approach\n"

    sections.extend([
        "## Eligibility criteria\n",
        "**Inclusion:**\n",
        _format_criteria(cfg.inclusion),
        "\n**Exclusion:**\n",
        _format_criteria(cfg.exclusion),
        "\n## Information sources\n",
        _format_information_sources(cfg, prospective=prospective),
        search_heading,
        _format_planned_search_strategy(cfg, paths),
        "\n## Seed papers and inspiration\n",
        _format_seeds(cfg.seeds),
        screening_heading,
        _format_screening_plan(cfg, prospective=prospective),
        extraction_heading,
        _format_data_extraction(cfg, prospective=prospective),
        rob_heading,
        _format_quality_assessment_plan(paths, prospective=prospective),
    ])
    return sections


def _query_summary(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute(
        "SELECT query_id, source, query_string, executed_at, result_count, notes "
        "FROM queries ORDER BY executed_at"
    ).fetchall()
    out = [dict(r) for r in rows]
    # Searches run before request failures were stored with the query only
    # have them in the event log (silent-zero / partial-coverage events).
    problems: dict[str, str] = {}
    for e in conn.execute(
        "SELECT message, payload_json FROM events "
        "WHERE stage = 'search' AND level IN ('error', 'warning') ORDER BY id"
    ).fetchall():
        try:
            query_id = json.loads(e["payload_json"] or "{}").get("query_id")
        except (ValueError, AttributeError):
            continue
        if query_id:
            problems.setdefault(query_id, e["message"])
    for q in out:
        if not q.get("notes") and q["query_id"] in problems:
            q["notes"] = problems[q["query_id"]]
    return out


def _decision_counts(conn: sqlite3.Connection, pass_name: str) -> dict:
    """Final decisions per pass, picking the best decided_by per record."""
    rows = conn.execute(
        """
        WITH ranked AS (
            SELECT record_id, decision,
                   ROW_NUMBER() OVER (
                       PARTITION BY record_id
                       ORDER BY CASE decided_by
                         WHEN 'human' THEN 1
                         WHEN 'agent' THEN 2
                         ELSE 3 END
                   ) AS r
            FROM screening WHERE pass = ?
        )
        SELECT decision, COUNT(*) AS n FROM ranked WHERE r = 1
        GROUP BY decision
        """,
        (pass_name,),
    ).fetchall()
    return {r["decision"]: r["n"] for r in rows}


def _included_record_count(conn: sqlite3.Connection) -> int:
    row = conn.execute(
        """
        SELECT COUNT(*) AS n
        FROM records r
        WHERE COALESCE(
            (SELECT decision FROM screening
             WHERE record_id=r.id AND pass='full_text'
             ORDER BY CASE decided_by
               WHEN 'human' THEN 1
               WHEN 'agent' THEN 2
               ELSE 3 END LIMIT 1),
            (SELECT decision FROM screening
             WHERE record_id=r.id AND pass='title_abstract'
             ORDER BY CASE decided_by
               WHEN 'human' THEN 1
               WHEN 'agent' THEN 2
               ELSE 3 END LIMIT 1)
        ) = 'include'
        """
    ).fetchone()
    return int(row["n"] or 0)


def _flow_counts(conn: sqlite3.Connection) -> dict:
    """Pull counts needed for PRISMA flow diagrams and methodology prose."""
    out: dict[str, Any] = {}
    out["records_total"] = conn.execute(
        "SELECT COUNT(*) AS n FROM records"
    ).fetchone()["n"]

    # Records identified per source. Fuzzy dedup used to delete the hits it
    # merged, so in older projects those hits survive only in dedup_log.
    out["per_source"] = {}
    for r in conn.execute(
        """
        SELECT source, COUNT(*) AS n FROM (
            SELECT source, COALESCE(source_id, 'hit:' || id) AS sid
            FROM source_hits
            UNION
            SELECT merged_source, merged_source_id FROM dedup_log
            WHERE merged_source_id IS NOT NULL
        )
        GROUP BY source
        """
    ).fetchall():
        out["per_source"][r["source"]] = r["n"]
    out["source_hits_total"] = sum(out["per_source"].values())

    out["sources_searched"] = conn.execute(
        "SELECT COUNT(DISTINCT source) AS n FROM queries"
    ).fetchone()["n"]

    out["dedup_merges"] = conn.execute(
        "SELECT COUNT(*) AS n FROM dedup_log"
    ).fetchone()["n"]
    # Exact-id matches at insert time and fuzzy merges together.
    out["duplicates_removed"] = max(
        out["source_hits_total"] - out["records_total"], 0
    )

    out["snowball_links"] = conn.execute(
        "SELECT COUNT(*) AS n FROM snowball_links"
    ).fetchone()["n"]
    out["snowball_by_direction"] = {}
    for r in conn.execute(
        "SELECT direction, COUNT(*) AS n FROM snowball_links GROUP BY direction"
    ).fetchall():
        out["snowball_by_direction"][r["direction"]] = r["n"]

    out["ta_decisions"] = _decision_counts(conn, "title_abstract")
    out["ft_decisions"] = _decision_counts(conn, "full_text")

    out["downloads"] = {}
    for r in conn.execute(
        "SELECT status, COUNT(*) AS n FROM downloads GROUP BY status"
    ).fetchall():
        out["downloads"][r["status"]] = r["n"]

    # Record-level retrieval (avoids inflating PRISMA with failed alt URLs)
    out["download_records"] = {
        "success": conn.execute(
            "SELECT COUNT(DISTINCT record_id) AS n FROM downloads "
            "WHERE status = 'success'"
        ).fetchone()["n"],
        "not_retrieved": conn.execute(
            """
            SELECT COUNT(DISTINCT d.record_id) AS n
            FROM downloads d
            WHERE d.record_id NOT IN (
                SELECT record_id FROM downloads WHERE status = 'success'
            )
              AND d.status IN ('failed', 'skipped_closed', 'skipped_no_license')
            """
        ).fetchone()["n"],
    }

    out["extractions_total"] = conn.execute(
        "SELECT COUNT(*) AS n FROM extractions"
    ).fetchone()["n"]
    out["extractions_with_quality"] = conn.execute(
        "SELECT COUNT(*) AS n FROM extractions "
        "WHERE methodological_rigor IS NOT NULL"
    ).fetchone()["n"]
    out["extractions_with_risk_of_bias"] = conn.execute(
        "SELECT COUNT(*) AS n FROM extractions "
        "WHERE risk_of_bias_overall IS NOT NULL AND risk_of_bias_overall != ''"
    ).fetchone()["n"]
    out["included_records"] = _included_record_count(conn)

    return out


def _format_search_strategy(queries: list[dict]) -> str:
    if not queries:
        return "_(no searches recorded)_\n"
    out = []
    for q in queries:
        when = q.get("executed_at", "")
        source = q.get("source", "")
        count = q.get("result_count", 0)
        query_string = str(q.get("query_string", ""))[:1000]
        out.append(f"**{source}** (executed {when}, returned {count} records)")
        if q.get("notes"):
            out.append(f"> Note: {q['notes']}")
        out.append(f"```\n{query_string}\n```")
    return "\n".join(out) + "\n"


def _format_flow_summary(flow: dict) -> str:
    lines = ["**Identification:**"]
    if flow["per_source"]:
        for source, count in flow["per_source"].items():
            label = "seed papers (user-supplied)" if source == "seed" else source
            lines.append(f"- {label}: {count} records")
    lines.append(f"- Total source-hits: {flow['source_hits_total']}")
    lines.append("")
    lines.append(
        f"**After deduplication:** {flow['records_total']} unique records "
        f"(removed {flow.get('duplicates_removed', flow['dedup_merges'])} duplicates)"
    )
    lines.append("")
    if flow["ta_decisions"]:
        lines.append("**Title/abstract screening:**")
        for decision, count in flow["ta_decisions"].items():
            lines.append(f"- {decision}: {count}")
        lines.append("")
    if flow["downloads"] or flow.get("download_records"):
        lines.append("**Full-text retrieval:**")
        dr = flow.get("download_records") or {}
        if dr:
            lines.append(f"- records retrieved: {dr.get('success', 0)}")
            lines.append(f"- records not retrieved: {dr.get('not_retrieved', 0)}")
        for status, count in (flow.get("downloads") or {}).items():
            if status in ("queued", "skipped_superseded"):
                continue
            lines.append(f"- {status}: {count}")
        lines.append("")
    if flow["ft_decisions"]:
        lines.append("**Full-text screening:**")
        for decision, count in flow["ft_decisions"].items():
            lines.append(f"- {decision}: {count}")
        lines.append("")
    if flow["snowball_links"]:
        lines.append(f"**Snowball sampling:** {flow['snowball_links']} new links")
        for direction, count in flow["snowball_by_direction"].items():
            lines.append(f"- {direction}: {count}")
        lines.append("")
    if flow["extractions_total"]:
        lines.append(
            f"**Extraction:** {flow['extractions_total']} records "
            f"(legacy quality fields: {flow['extractions_with_quality']})"
        )
        lines.append(
            "**Risk of bias:** "
            f"{flow.get('extractions_with_risk_of_bias', 0)} records assessed"
        )
        lines.append("")
    return "\n".join(lines)


def _screening_breakdown(conn: sqlite3.Connection) -> list[dict]:
    rows = conn.execute(
        """
        SELECT pass, decided_by, decision, COUNT(*) AS n
        FROM screening
        GROUP BY pass, decided_by, decision
        ORDER BY pass, decided_by, decision
        """
    ).fetchall()
    return [dict(r) for r in rows]


def _format_screening_breakdown(rows: list[dict]) -> str:
    if not rows:
        return "_(no screening decisions recorded)_\n"
    out = []
    current_pass = None
    for row in rows:
        pass_name = row["pass"]
        if pass_name != current_pass:
            if current_pass is not None:
                out.append("")
            out.append(f"**{pass_name}:**")
            current_pass = pass_name
        out.append(f"- {row['decided_by']} / {row['decision']}: {row['n']}")
    return "\n".join(out) + "\n"


def generate_protocol_draft(cfg: ProjectConfig, paths: ProjectPaths) -> str:
    """Generate the prospective protocol draft as a string."""
    sections = _base_sections(
        cfg,
        paths,
        title="Protocol Draft",
        prospective=True,
    )
    sections.append(REGISTRATION_NOTE)
    return "\n".join(sections)


def generate_methodology_report(cfg: ProjectConfig, paths: ProjectPaths) -> str:
    """Generate the retrospective methodology report as a string."""
    sections = _base_sections(
        cfg,
        paths,
        title="Methodology Report",
        prospective=False,
    )

    db_path = paths.db
    if db_path.exists():
        with sqlite3.connect(db_path) as conn:
            conn.row_factory = sqlite3.Row
            queries = _query_summary(conn)
            flow = _flow_counts(conn)
            screening = _screening_breakdown(conn)
        sections.extend([
            "\n## Search strategy as executed\n",
            _format_search_strategy(queries),
            "\n## Flow summary\n",
            _format_flow_summary(flow),
            "\n## Screening procedure as run\n",
            _format_screening_breakdown(screening),
            "\n## Risk-of-bias assessments recorded\n",
            (
                "Risk-of-bias assessments recorded: "
                f"**{flow.get('extractions_with_risk_of_bias', 0)}** "
                f"out of **{flow.get('included_records', 0)}** included records.\n"
            ),
        ])
    else:
        sections.extend([
            "\n## Search strategy as executed\n",
            "_(project database not found; searches not recorded)_\n",
            "\n## Flow summary\n",
            "_(project database not found; flow counts unavailable)_\n",
            "\n## Screening procedure as run\n",
            "_(project database not found; screening counts unavailable)_\n",
            "\n## Risk-of-bias assessments recorded\n",
            "_(project database not found; assessment counts unavailable)_\n",
        ])

    sections.extend([
        REGISTRATION_NOTE,
        "\n## Engine version and audit\n",
        f"Generated by SLR-Engine {SLR_ENGINE_VERSION}.\n",
        "Full audit log: `audit.json` (queries, dedup decisions, screening "
        "labels, snowball links, downloads, and events).\n",
    ])

    return "\n".join(sections)


def write_protocol_draft(cfg: ProjectConfig, paths: ProjectPaths) -> Path:
    """Generate and write protocol_draft.md to the project root."""
    out_path = paths.root / "protocol_draft.md"
    out_path.write_text(generate_protocol_draft(cfg, paths), encoding="utf-8")
    return out_path


def write_methodology_report(cfg: ProjectConfig, paths: ProjectPaths) -> Path:
    """Generate and write methodology_report.md to exports/."""
    paths.exports.mkdir(parents=True, exist_ok=True)
    out_path = paths.exports / "methodology_report.md"
    out_path.write_text(generate_methodology_report(cfg, paths), encoding="utf-8")
    return out_path


def generate_protocol(cfg: ProjectConfig, paths: ProjectPaths) -> str:
    """Deprecated compatibility wrapper for generate_methodology_report()."""
    return generate_methodology_report(cfg, paths)


def write_protocol(cfg: ProjectConfig, paths: ProjectPaths) -> Path:
    """Deprecated compatibility wrapper for write_methodology_report()."""
    return write_methodology_report(cfg, paths)
